project:
  type: website

website:
  title: "Data Wow"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/QuantPsych
      - icon: twitter
        href: https://twitter.com/dr_tofighi
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

