baseURL = "https://data-wow.netlify.app/"
languageCode = "en-US"
title = "Data Wow: From Data to Discovery"
theme = "PaperMod"

[build]
command = 'hugo'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.118.2'

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'
